spring.application.name=serratemusic
server.port=9090

spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true


spring.datasource.url=jdbc:postgresql://localhost:5432/serratecmusic
spring.datasource.username=postgres
spring.datasource.password=pedro2505
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jackson.deserialization.fail-on-unknown-properties=true
